// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmlJIwpuEldBWk2s1i2UZyXiO5f-Ur-yU',
    appId: '1:952996561147:web:0b63a86be21d848e8fb05e',
    messagingSenderId: '952996561147',
    projectId: 'i-like-it-39136',
    authDomain: 'i-like-it-39136.firebaseapp.com',
    storageBucket: 'i-like-it-39136.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHgRrutCusIxQfNtO89LYL18qK9zZBbE',
    appId: '1:952996561147:android:dc32a013deff34908fb05e',
    messagingSenderId: '952996561147',
    projectId: 'i-like-it-39136',
    storageBucket: 'i-like-it-39136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNoUk7QLvqV-JodHSXbARf2m3LjoR-C4E',
    appId: '1:952996561147:ios:e6f20a306958140a8fb05e',
    messagingSenderId: '952996561147',
    projectId: 'i-like-it-39136',
    storageBucket: 'i-like-it-39136.firebasestorage.app',
    iosBundleId: 'com.example.linkSaverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNoUk7QLvqV-JodHSXbARf2m3LjoR-C4E',
    appId: '1:952996561147:ios:e6f20a306958140a8fb05e',
    messagingSenderId: '952996561147',
    projectId: 'i-like-it-39136',
    storageBucket: 'i-like-it-39136.firebasestorage.app',
    iosBundleId: 'com.example.linkSaverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmlJIwpuEldBWk2s1i2UZyXiO5f-Ur-yU',
    appId: '1:952996561147:web:9b285b079455a4ac8fb05e',
    messagingSenderId: '952996561147',
    projectId: 'i-like-it-39136',
    authDomain: 'i-like-it-39136.firebaseapp.com',
    storageBucket: 'i-like-it-39136.firebasestorage.app',
  );
}
